name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # build
    - run: cp .env.example .env
    - run: make dev

    # upload data-structures
    - uses: actions/upload-artifact@v2
      with:
        name: data-structures
        path: data-structures

    # upload helpers
    - uses: actions/upload-artifact@v2
      with:
        name: helpers
        path: helpers

    # upload server
    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: server
        
  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

      # test data-structures
    - uses: actions/download-artifact@v2
    - run: chmod -R +x ./* 
      working-directory: data-structures/tests
    - run: cp .env.example .env
    - run: make -s tests
      working-directory: data-structures/tests

    # test helpers
    - uses: actions/download-artifact@v2
    - run: chmod -R +x ./*
      working-directory: helpers/tests
    - run: cp .env.example .env
    - run: make -s tests
      working-directory: helpers/tests

    # test server
    - uses: actions/download-artifact@v2
    - run: chmod -R +x ./*
      working-directory: server/tests
    - run: cp .env.example .env
    - run: make -s tests
      working-directory: server/tests
