name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd data-structures/tests
    - run: make dev
    
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make -s tests
