name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make data-structures tests
      run: cd data-structures/tests && make
    - name: run tests
      run: cd data-structures/tests *.c
