name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make dev
    - uses: actions/upload-artifact@v2
      with:
        name: data-structures-build
        path: data-structures
    - uses: actions/upload-artifact@v2
      with:
        name: helpers-build
        path: helpers
        
  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - run: make -s tests
      working-directory: data-structures-build/tests
