name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # build
    - run: cp .env.test .env
    - run: make dev

    # upload the project
    - uses: actions/upload-artifact@v2
      with:
        name: in-memory-file-storage-server
        path: ${{ github.workspace }}
        
  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: in-memory-file-storage-server

    # unit test
    - name: Run unit tests
      run: cp .env.test .env && chmod -R +x * && make -s tests

    # valgrind test
    - name: Run valgrind tests
      run: cp .env.test .env && chmod -R +x * && make -s tests-valgrind

    # valgrind-short test
    - name: Run valgrind-short tests
      run: cp .env.test .env && chmod -R +x * && make -s tests-valgrind-short